### ISSUE TITLE
Weird XML string from ToXml()

### ISSUE THREAD

**Issue by philjones88** [a-gubskiy/X.Web.Sitemap#1]
Hi,

Trying to use your project to generate an XML sitemap string I can return to the client's browser.

Problem is I end up with something like:

``` xml

<?xml version="1.0" encoding="utf-8"?><ArrayOfUrl xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/X.Web.Sitemap"><Url><_x003C_ChangeFrequency_x003E_k__BackingField>Weekly</_x003C_ChangeFrequency_x003E_k__BackingField><_x003C_Location_x003E_k__BackingField>/payment-protection</_x003C_Location_x003E_k__BackingField><_x003C_Priority_x003E_k__BackingField>0.5</_x003C_Priority_x003E_k__BackingField><_x003C_TimeStamp_x003E_k__BackingField>2013-04-04T00:00:00</_x003C_TimeStamp_x003E_k__BackingField></Url>

```

Strangely from the ToXml() method, the Save() method saves it fine to a physical file.

Any ideas? Thanks for any help you can provide.

**Comment by a-gubskiy** [comment]
I cant reproduce your situation, but i changed inner logic.
Now i using XmlSerializer for generate xml. 
Try now to generate xml.
