### ISSUE TITLE
ArrayOfUrl instead of urlset?

### ISSUE THREAD

**Issue by pboisso** [a-gubskiy/X.Web.Sitemap#12]
Hi,

For some reason, when generating sitemaps, the list of url is getting out as

`<ArrayOfUrl xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <url>
...`

instead of
`<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
...`

Any idea why?

Got the nuget 2.0.5 version.

Thanks.

**Comment by VagyokC4** [comment]
@ernado-x Has or is this issue being addressed?

**Comment by atrevido** [comment]
There is a bug in ISitemapGenerator (SitemapGenerator.cs)

It uses incorrect serializer

`_serializedXmlSaver = new SerializedXmlSaver<List<Url>>(new FileSystemWrapper());`

instead of 

`_serializedXmlSaver = new SerializedXmlSaver<Sitemap>(new FileSystemWrapper());`

**Comment by atrevido** [comment]
And as i can see it works so only if you use generator with sitemap index. In case of a simple sitemap it's ok

**Comment by tsteele** [comment]
I updated my fork with the change , but it still generating ArrayOfUrl  in the xml. Even running the unit test generates files with ArrayOfUrl .
