### ISSUE TITLE
Net core support

### ISSUE THREAD

**Issue by imclint21** [a-gubskiy/X.Web.Sitemap#19]
Hey hey,

I add X.Web.Sitemap on my app and i've a warning
```
***.csproj : warning NU1701: Le package 'X.Web.Sitemap 1.0.0' a été restauré en utilisant '.NETFramework,Version=v4.6.1' au lieu du framework cible du projet '.NETCoreApp,Version=v2.2'. Ce package n'est peut-être pas totalement compatible avec votre projet.```
```
Do you will publish a netstandard lib ?

Thanks

**Comment by a-gubskiy** [comment]
.NET Core support with .NET Standard already implemented

But project can be build both for .NET Standard and classic .NET.

You need add nugget package from here: https://nuget.org/packages/xsitemap

**Comment by imclint21** [comment]
Nice
