### ISSUE TITLE
Support time in lastmod datetime string value

### ISSUE THREAD

**Issue by Ju66ernaut** [a-gubskiy/X.Web.Sitemap#21]
I would like to support having time included in the lastmod value of the xmlsitemap

I have a collection of data that I am using to create the xmlsitemap  `results`. 
`
results.ForEach(r =>
	{
		sitemap.Add(new Url()
			{
				Location = r.loc,
				LastMod = String.Format("{0:s}", r.lastmod)
			});
	});
`

The format configuration I am using is outputting my datetimes like this `2020-05-27T17:02:00` but the "get" logic later in the X.Web.Sitemap code is parsing the datetime value to just be the date string so it outputs the values in the xmlsitemap to be `<lastmod>2020-05-27</lastmod>`

I understand it is making sure the string passed in is a valid date time but it is assuming I only want the date string.

**Comment by a-gubskiy** [comment]
Closed by #22 
Thank you!
