### ISSUE TITLE
Support of Sitemap Index Files

### ISSUE THREAD

**Issue by codingyourlife** [a-gubskiy/X.Web.Sitemap#32]
I ran into the issue that more than 50000 entries are too much for google. Seems this library takes care of it when using SaveToDirectory() function.  But there is no index file.

Index file:
https://www.sitemaps.org/protocol.html#index

**Comment by a-gubskiy** [comment]
This is already implemented. Please see [example](https://github.com/ernado-x/X.Web.Sitemap/blob/master/src/X.Web.Sitemap.Example/SitemapGenerationWithSitemapIndexExample.cs#L18).
