### ISSUE TITLE
Bug: Nullref in SaveToDirectory()

### ISSUE THREAD

**Issue by codingyourlife** [a-gubskiy/X.Web.Sitemap#33]
The problem is even bigger because you might just end up with an incomplete result not noticing that your api call crashed because of the try catch return false!

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/10122382/188203360-7896e0e0-5eba-4bd0-81af-f1d479458c99.png">

What I did special is this:
`Sitemap.DefaultMaxNumberOfUrlsPerSitemap = 50000; //50000 is google maximum`

Before:
`var sitemap = new Sitemap();`

**Comment by codingyourlife** [comment]
after fixing the nullref it creates sitemap0.xml - sitemap5.xml but except sitemap0.xml all others are empty

**Comment by codingyourlife** [comment]
There is also a division by zero error ^^
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/10122382/188213614-c52d82ea-f6c5-4ab9-b994-69d0a003cb5c.png">

**Comment by codingyourlife** [comment]
@ernado-x I can see that you've attempted to fix in a new version here:
https://github.com/ernado-x/X.Web.Sitemap/pull/30

but that's already 9 months old...

**Comment by codingyourlife** [comment]
@ernado-x  here is my quickfix solution proposal.
https://github.com/ernado-x/X.Web.Sitemap/pull/34

take it or leave it. I can see you seem to be active now working on it :)

**Comment by a-gubskiy** [comment]
Own sitemap saving was replaced by [SitemapGenerator](https://github.com/ernado-x/X.Web.Sitemap/blob/master/src/X.Web.Sitemap/SitemapGenerator.cs) implementation.

Also you can now configure [MaxNumberOfUrlsPerSitemap](https://github.com/ernado-x/X.Web.Sitemap/blob/master/src/X.Web.Sitemap/SitemapGenerator.cs#L13) option.
