### ISSUE TITLE
Utf8 issue

### ISSUE THREAD

**Issue by codingyourlife** [a-gubskiy/X.Web.Sitemap#36]
Google says [here](https://developers.google.com/search/docs/advanced/sitemaps/build-sitemap#xml):
Sitemap files must be UTF-8 encoded, and [URLs escaped](https://developers.google.com/search/docs/advanced/sitemaps/build-sitemap#sitemap-encoding-guidelines) appropriately.

[This validator](https://www.xml-sitemaps.com/validate-xml-sitemap.html) showed me an error until I manually programatically modified first line of xml to be utf-8 instead of 16 and extended FileSystemWrapper.cs to have Encoding.UTF8 as 3rd argument to StreamWriter.

**Comment by codingyourlife** [comment]
I do it like that to get rid of xmlns:* which is not part of google search console help page and to change utf-16 to utf-8

var xmlString = xmlDocument.ToXmlString();
xmlString = Regex.Replace(xmlString, @" xmlns:.*?"".*?""", "");
xmlString = xmlString.Replace("encoding=\"utf-16\"", "encoding=\"utf-8\"");

and for file save as said FileSystemWrapper needs to be changed (highlighted part)
<img width="704" alt="image" src="https://user-images.githubusercontent.com/10122382/188278125-e061ddd2-7d56-43da-96cc-ddf6cb799ec1.png">

@ernado-x can this (especially the image) be changed any time soon?

**Comment by a-gubskiy** [comment]
@codingyourlife could you please provide example code where you receive utf-16?
