### ISSUE TITLE
Please add support for image sitemaps

### ISSUE THREAD

**Issue by ErcinDedeoglu** [a-gubskiy/X.Web.Sitemap#38]
Is it possible to add this support?
https://developers.google.com/search/docs/crawling-indexing/sitemaps/image-sitemaps

**Comment by nsnlookupjn** [comment]
Such a great library - adding image and video support would make it complete and much more powerful

**Comment by a-gubskiy** [comment]
@ErcinDedeoglu @nsnlookupjn please have a look this version https://www.nuget.org/packages/xsitemap/2.7.1-beta

**Comment by nsnlookupjn** [comment]
Thank you for the release. You will see that the XML structure is not quite right. This code is generating a list of "<images>" of <image> where sitemaps require a repeating <image:image> structure with <image:loc> as the url element. Reference document is https://developers.google.com/search/docs/crawling-indexing/sitemaps/image-sitemaps

**Comment by nsnlookupjn** [comment]
Corrected: Thank you for the release. You will see that the XML structure is not quite right. This code is generating a list "Images" of "Image" where sitemaps require a repeating "image:image" structure with "image:loc" as the url element. Reference document is https://developers.google.com/search/docs/crawling-indexing/sitemaps/image-sitemaps

**Comment by ErcinDedeoglu** [comment]
Hey @ernado-x , thank you so much for the feature.
This will help a lot.

I just confirmed that XML has an error ~Google

![image](https://user-images.githubusercontent.com/6512072/220083675-8e3044e0-3ef8-4b08-9481-03d08f0cc05d.png)

`<url>
<loc>https://www.x.com/u/jo2</loc>
<lastmod>2020-03-10T11:01:12+00:00</lastmod>
<changefreq>yearly</changefreq>
<priority>0.5</priority>
</url>
<url>
<loc>https://www.x.com/u/eYc</loc>
<Images>
<image>
<loc>https://fs.x.com/image/60185/unnamed.png</loc>
</image>
</Images>
<lastmod>2020-04-18T13:12:19+00:00</lastmod>
<changefreq>yearly</changefreq>
<priority>0.5</priority>
</url>`

**Comment by a-gubskiy** [comment]
@ErcinDedeoglu @nsnlookupjn please have a look new version https://www.nuget.org/packages/xsitemap/2.7.2-beta
