### ISSUE TITLE
Why there are no methos ToXml in SitemapIndex?

### ISSUE THREAD

**Issue by bazarniy** [a-gubskiy/X.Web.Sitemap#65]
Hello! It would be pretty to have ToXml method in SitemapIndex too. It will give similar code when use Sitemap and SitemapIndex in response generation

**Comment by Bodokh** [comment]
I second this, as well as suggest to add some sort of toStream method since today the world is moving to stateless so let the developer choose how to save the data wether its a local file or to S3 and so on.
