### ISSUE TITLE
DefaultMaxNumberOfUrlsPerSitemap is 5000

### ISSUE THREAD

**Issue by TimurZanagar** [a-gubskiy/X.Web.Sitemap#72]
The Property DefaultMaxNumberOfUrlsPerSitemap is set to 5.000 and not to 50.000 as recommended.

References: 
- https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap#sitemap-best-practices

Sitemap size limits: All formats limit a single sitemap to 50MB (uncompressed) or 50,000 URLs. If you have a larger file or more URLs, you must break your sitemap into multiple sitemaps. You can optionally create a [sitemap index](https://developers.google.com/search/docs/crawling-indexing/sitemaps/large-sitemaps) file and submit that single index file to Google. You can submit multiple sitemaps and sitemap index files to Google. This may be useful if you want to track the search performance of each individual sitemap in Search Console.

**Comment by a-gubskiy** [comment]
Closed by #73

**Comment by TimurZanagar** [comment]
@ernado-x Thank you very much for the fast response! Is it possible to create a v2.9.3 Release? I would like to use these changes.
