### ISSUE TITLE
Not able to override DefaultMaxNumberOfUrlsPerSitemap

### ISSUE THREAD

**Issue by TimurZanagar** [a-gubskiy/X.Web.Sitemap#74]
Hi,

Since there is no new version, I tried to override the DefaultMaxNumberOfUrlsPerSitemap property with no luck. Is it possible to create a new release or to give me an example to get this done?

Cheers Timur

**Comment by a-gubskiy** [comment]
You can do it as it defined here: https://github.com/ernado-x/X.Web.Sitemap/blob/b1c0a21947b7260b21df795ebe4f20f8570462c3/src/X.Web.Sitemap.Example/Program.cs#L7

Also new version is published, but for backward compatibility the implementation little bit changes.
