### ISSUE TITLE
SitemapsForMyEntireWebsite

### ISSUE THREAD

**Issue by bobbymale** [a-gubskiy/X.Web.Sitemap#8]
I'm having brain freeze and can't figure out how to pass one url and go thru 3 or more level deep of the main url.

**Comment by a-gubskiy** [comment]
Please, describe your problem  more detail

**Comment by bobbymale** [comment]
Sure sorry I was out of town. I took this sample GenerateSitemapsForMyEntireWebsite then trying to crawl all links http://www.example.com but somehow don't know how to use this class. I am using console project.
